version: 1.0.{build}

image: Visual Studio 2019

platform: x64

environment: 
  matrix:
    - compiler: msvc2019
    - compiler: msys2
    
install:
  - cmd: |-
      git submodule update --init --recursive
      
build_script:
  - cmd: |-
      %APPVEYOR_BUILD_FOLDER%\.appveyor\appveyor_build_qasm.bat
      %APPVEYOR_BUILD_FOLDER%\.appveyor\appveyor_build_qiskit.bat

test_script:
  - cmd: |-
      %APPVEYOR_BUILD_FOLDER%\.appveyor\appveyor_test_qasm.bat
      %APPVEYOR_BUILD_FOLDER%\.appveyor\appveyor_test_qiskit.bat
